variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build:
  stage: build
  script:
    - pip install -r requirements.txt

test:
  stage: test
  retry: 2
  script:
    - pip install -r requirements.txt
    - python setup.py test
    - coverage run setup.py test
    - coverage report -m

# This essentially tests whether or not the program can be run by invoking
# "pyarcade" at the command-line.
deploy_test:
  stage: test
  retry: 2
  script:
    - pip install -r requirements.txt
    - python setup.py install
    - pyarcade
